#!/bin/bash

source $( dirname $( readlink -f $0 ))/../commons
imagetag=$( get-image-tag $0 )

init-default-settings
workingdir=$( validate-dir $1 ) || exit $?
ports=8000

posts_dir=$( validate-dir "$2" "_posts" ) || exit $?
posts_dir=$( validate-dir "$3" "blogres" ) || exit $?
add_args="-v $2:/workdir/_posts -v $3:/workdir/res/blogres"

build-docker-image $0
re-run-docker-container \
server -s /workdir -d /workdir/_site --port 8000 --host 0.0.0.0
