#!/bin/bash

cd "$( dirname "$( readlink -f "$0" )" )"
source ../commons
imagetag=$( get-image-tag )

init-default-settings
rmcontainer=1

build-docker-image
[ $? != 0 ] && exit 1
re-run-docker-container $@
