#!/bin/bash

cd "$( dirname "$( readlink -f "$0" )" )"
source ../commons
imagetag=$( get-image-tag )

init-default-settings
workingdir=$( validate-working-dir $1 ) || exit $?
rmcontainer=0

build-docker-image
[ $? != 0 ] && exit 1
re-run-docker-container bash
