#!/bin/bash

source $( dirname $( readlink -f $0 ))/../commons
imagetag=$( get-image-tag $0 )

init-default-settings
workingdir=$( validate-dir $1 ) || exit $?
runaslocaluser=1

build-docker-image $0
[ $? != 0 ] && exit 1
re-run-docker-container bash
