#!/bin/bash

source $( cd "$( dirname "$0" )"; pwd )/../commons
imagetag=$( get-image-tag $0 )

init-default-settings
rmcontainer=0

build-docker-image $0
[ $? != 0 ] && exit 1
re-run-docker-container $@
