#!/bin/bash

cd "$( dirname "$( readlink -f "$0" )" )"
source ../docker-commons
imagetag=$( get-image-tag )

init-default-settings
workingdir=$( validate-working-dir $@ ) || exit $?
xorg=1

build-docker-image
re-run-docker-container
